import os.path

# Field validation settings
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 50

EMAIL_MAX_LENGTH = 50

FIRST_NAME_MIN_LENGTH = 2
FIRST_NAME_MAX_LENGTH = 50

MIDDLE_NAME_MIN_LENGTH = 2
MIDDLE_NAME_MAX_LENGTH = 50

LAST_NAME_MIN_LENGTH = 2
LAST_NAME_MAX_LENGTH = 50

CHARFIELD_MAX_LENGTH = 50

# Avatar settings
AVATAR_PATH = "users/avatars/"
DEFAULT_AVATAR_NAME = "default_avatar.png"
DEFAULT_AVATAR_PATH = os.path.join(AVATAR_PATH, DEFAULT_AVATAR_NAME)
AVATAR_MAX_SIZE = (300, 300)
AVATAR_QUALITY = 85         # quality JPEG

# Confirmation code
CODE_LENGTH = 4
CODE_EXPIRATION = 5         # minutes
